config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_by_default: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_spacemacs:
    dst: ~/.spacemacs
    src: .spacemacs
profiles:
  arch:
    dotfiles:
    - f_spacemacs
