config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_by_default: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_aliases:
    dst: ~/.aliases
    src: .aliases
  f_bashrc:
    dst: ~/.bashrc
    src: .bashrc
  f_environ:
    dst: ~/.environ
    src: .environ
  f_spacemacs:
    dst: ~/.spacemacs
    src: .spacemacs
profiles:
  arch:
    dotfiles:
    - f_spacemacs
    - f_aliases
    - f_environ
    - f_bashrc
