config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_spacemacs:
    dst: ~/.spacemacs
    src: .spacemacs
  f_config_nvim_init.vim:
    src: .config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    link: link
  f_bashrc:
    src: .bashrc
    dst: ~/.bashrc
  d_config_bash:
    src: .config/bash
    dst: ~/.config/bash
profiles:
  arch:
    dotfiles:
    - f_spacemacs
    - f_config_nvim_init.vim
    - f_bashrc
    - d_config_bash
