config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_spacemacs:
    dst: ~/.spacemacs
    src: .spacemacs
  f_config_nvim_init.vim:
    src: .config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_aliases.bash:
    src: .aliases.bash
    dst: ~/.aliases.bash
  f_environ.bash:
    src: .environ.bash
    dst: ~/.environ.bash
  f_colors.bash:
    src: .colors.bash
    dst: ~/.colors.bash
  f_bashrc:
    src: .bashrc
    dst: ~/.bashrc
profiles:
  arch:
    dotfiles:
    - f_spacemacs
    - f_config_nvim_init.vim
    - f_aliases.bash
    - f_environ.bash
    - f_colors.bash
    - f_bashrc
