prompt_order = [
    "time",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "python",
    "rust",
    "memory_usage",
    "env_var",
    "cmd_duration",
    "jobs",
    "battery",
    "line_break",
    "character",
]

[character]
symbol = "└─ $"
error_symbol = "└─ ✗"
use_symbol_for_status = true
style_success = "bold green"
style_failure = "bold green"

[memory_usage]
show_percentage = true
disabled = false

[git_branch]
style = "yellow"

[time]
disabled = false
style = "green"
format = "[%T]"

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 5

[package]
disabled = true

[jobs]
symbol = "✦ "

[python]
symbol = ""
pyenv_version_name = true
pyenv_prefix = ""
