format = """\
    $time\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $python\
    $rust\
    $terraform\
    $aws\
    $memory_usage\
    $env_var\
    $cmd_duration\
    $jobs\
    $battery\
    $line_break\
    $character\
    """
[aws]
format = "on [$symbol$profile]($style) "
style = "bold blue"

[character]
success_symbol = "[└─ \\$](bold green)"
error_symbol = "[└─ ✗](bold green)"

[memory_usage]
show_percentage = true
threshold = 90
disabled = false

[git_branch]
style = "bold yellow"

[time]
disabled = false
style = "bold green"
format = "[$time]($style) "
time_format = "[%T]"

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 5

[package]
disabled = true

[jobs]
symbol = "✦ "

[python]
symbol = ""
